spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: mydest
        output:
          destination: myprocdest
          
server.port: 8099