spring:
 
  profiles.active: default
  
---
spring:
  profiles: default
  
  
spring.datasource.url: jdbc:mysql://localhost/test
spring.datasource.username: root
spring.datasource.password:
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.kafka.bootstrap-servers: localhost:9092
spring.kafka.consumer.group-id: mysql-group
mysql.kafka.topic: mysql-springboot-topic
    
  
   
 